### ISSUE TITLE
是否可以更新关于ClashForAndroid3的教程？

### ISSUE THREAD

**Issue by WanCixiong** [Direct5dom/Direct5dom.github.io#1]
首先，对在Github上叨扰你感到抱歉，我没有在你的网站上找到评论的功能，所以出此下策。
我看到你在“【弃用】Clash for Magisk简明教程（v3.5.1）”提到了你使用了 Clash For Android3的TUN模式以代替ForMagisk，也表明了需要Root权限。我不清楚如何激活该软件的Root模式，在尝试时发现它声明的是Shizuku模式，我目前使用的是Kitsune Mask（狐狸面具） 没有采用Shizuku，我是不是需要使用Shizuku才能为它激活？   
有兴趣出一个ClashForMagisk3的教程吗？因为它和v2版本差别有点大。我没有网络上也没有搜到关于v3的教程。

**Comment by Direct5dom** [comment]
其实很简单，没必要单独写个教程，简单给你讲一下吧。

> 首先要说Clash For Android和之前一众Clash项目一样删库了，Clash For Android 3是当时开发者本人在群里小范围测试的版本，你得先获得这个版本，我之前保存了一份，可在这里获取：https://t.me/DHCP_Error

1. Clash For Android并不通过Root管理器（比如Magisk和KernelSU）获取Root权限，它通过Shizuku来获取所需要的功能和接口，而对于已经获取Root权限的手机，比起Shizuku APP，我更推荐刷入`Sui`模块，这样避免了Shizuku App响应和被检测的问题，你可以在这里获得：https://github.com/RikkaApps/Sui/releases
2. 当你安装好`Sui`之后打开CFA3 -> 点击右下角设置 -> 点击最上方启动模式（默认为“基础模式）-> Shizuku模式左下角的管理 -> 在自动弹出的授权窗口中选择始终允许 -> 将CFA3切换到Shizuku模式。
3. 添加Clash订阅或配置文件的过程应该不需多言。
4. 回到首页，此时你可以看到下方第二个选项就是`TUN`，打开右侧的开关即可。

**Comment by WanCixiong** [comment]
谢谢





其实很简单，没必要单独写个教程，简单给你讲一下吧。

首先要说Clash For Android和之前一众Clash项目一样删库了，Clash For Android 3是当时开发者本人在群里小范围测试的版本，你得先获得这个版本，我之前保存了一份，可在这里获取：https://t.me/DHCP_Error

Clash For Android并不通过Root管理器（比如Magisk和KernelSU）获取Root权限，它通过Shizuku来获取所需要的功能和接口，而对于已经获取Root权限的手机，比起Shizuku APP，我更推荐刷入Sui模块，这样避免了Shizuku App响应和被检测的问题，你可以在这里获得：https://github.com/RikkaApps/Sui/releases
当你安装好Sui之后打开CFA3 -> 点击右下角设置 -> 点击最上方启动模式（默认为“基础模式）-> Shizuku模式左下角的管理 -> 在自动弹出的授权窗口中选择始终允许 -> 将CFA3切换到Shizuku模式。
添加Clash订阅或配置文件的过程应该不需多言。
回到首页，此时你可以看到下方第二个选项就是TUN，打开右侧的开关即可。
